### ISSUE TITLE
Checklist for launch

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle.xyz#29]
Decided to merge in the PR #26 already. Took the checklist out and brought it over here. We can finish of the list on Monday and ship

@jameshaydon @jkarni @hxrts @xla @MeBrei 
- operational work
  - [x] port radicle over to radicle org
- Website work
  - [x] replace `diff` with `patch`
  - Front page
    - [x] in 3 value props
      - [x] P2P: make copy more concrete
      - [x] Terminal first: be explicit that projects contain repo + issue + patch in cli
      - [x] programmable: something like "ever dream of creating your own issues app..."
    - [x] apps -> utilities
      - [x] make asciinema > static + highlight some functionality
      - [x] setup a project: mention issues patches repo
      - [x] manage your issues: more to the point, call it "radicle issues" to decouple from GH??
      - [x] collabor... > "propose changes": mention that they are like super basic PR's?
    - [x] Stack / Architecture section:
      - [x] focus on giving a mental model of what is going on
      - [x] illustration update + clean up
      - [x] link should go to architecture section
    - [x] footer: think of issues being there before mentioning it
  - docs
    - [x] intro
      - [x] case for radicle > FAQ
      - [x] get involved > own section in bottom of docs
      - [x] new section: WHAT IS RADICLE
    - [x] Installation
      - [x] mention manually running the daemon in OSX and Debian sections
    - [x] Guide
      - [x] around `rad diff propose HEAD` section
        - [x] HEAD > hash
        - [x] explain where author comes from
        - [x] single commit only disclaimer
        - [x] commit message fix
  - garden
    - [x] create garden rad project
    - [x] add 2 garden txt's
    - [x] create issue with comment
  - visual & front end
    - [x] fix image
    - [x] redo illustration
    - [x] style 404
    - [x] remove asciinema
    - [x] fix responsiveness on docs 
    - [ ] Newsletter
    - [ ] add active state for links in docs and header
    - [x] add favicon
    - [x] links in footer broken (mailto - irc)
    - [ ] single blog post pages
    - [ ] radicle.xyz google bucket
  - Language ambiguity
    - [x] diff, patches, proposals, ...
    - [x] tutorial 1: commands should be code blocks in intro
    - [x] Doesn't know what a **proposal chain** is
    - [x] wording around proposals/diffs/patches is used in different places.
    - [x] in tutorial part 2 intro: "..., however..." is confusing
    - [x] in "what is radicle" section: "...as a Github/Gitlab replacement..." makes it sound like it's a full fledged alternative
    - [x] still mention "radicle apps"  in `radicle.rst`
    - [x] update radicle-garden repo readme
    - [x] Language needs an update in "what is radicle" Mentioning "github alternative" might be strong
- about page
  - [x] second paragraph was confusing
- dweb
  - [ ] dat URL
  - [ ] IPFS URL
  - [x] radicle project URL

**Comment by lftherios** [comment]
I was thinking that on the title we can use "A decentralized stack for code collaboration". And then on the 3 value props we can leave "peer-to-peer" but change the actual text to be more concrete.

**Comment by juliendonck** [comment]
I don't feel strongly about it so happy to change it. @hxrts @jkarni what do you think?

**Comment by hxrts** [comment]
I like P2P a little better personally. First, because there is a closer association with IPFS, Dat, and Scuttlebutt for some reason, while "decentralized" seems to be discussed more within blockchain communities.

We can maybe work decentralized in somewhere else.

**Comment by jkarni** [comment]
> I was thinking that on the title we can use "A decentralized stack for code collaboration". And then on the 3 value props we can leave "peer-to-peer" but change the actual text to be more concrete.

On the one hand I think it's nice to not have p2p show up as often. On the other:

1) I think "decentralized" is less precise - e.g. it could be blockchain-based. 
2) I think we should have the tagline be the same which we use in places like HN etc, and there p2p sounds better to me.

**Comment by lftherios** [comment]
thank you for the feedback. good with me!

**Comment by juliendonck** [comment]
Moved remaining items to #52
