### ISSUE TITLE
Post launch website checklist

### ISSUE THREAD

**Issue by juliendonck** [radicle-dev/radicle.xyz#52]
Things that didn't make it to the radicle alpha launch
- [ ] Newsletter
- [ ] add active state for links in docs and header
- [x] single blog post pages
- [x] dates and authors for blog posts
- [x] radicle.xyz google bucket
- [ ] dat url
- [ ] ipfs url
- [ ] analytics
- [ ] update radicle language docs

**Comment by juliendonck** [comment]
@jkarni moved the remaining topics to this issue, so we can close the other ones.

**Comment by hxrts** [comment]
Does this included styling the language docs as well?

**Comment by juliendonck** [comment]
Closing since this will get outdated quickly. Created a new issue for the ones in here I thought were still relevant. Which in my opinion is really only the `active state stuff`, if I'm being realistic.
